### PR TITLE
Update pcb-v2.1 to kicad4

### PR DESCRIPTION
**Pull request by rnestler**
I just opened the project with kicad4 and it needed to change some
components and I needed to remove the "special" library.

@dbrgn care to take a look at it? It shouldn't have changed a thing.

### CODE REVIEW

**Comment by dbrgn** [comment]
When opening the schema, I get this error message:

```
The following libraries were not found: rgb-led-v2-rescue
```

Where is that lib? And what was the `special` lib?

**Comment by rnestler** [comment]
According to http://www.tinkerunity.org/forum/index.php?topic=3242.0 the `special` library was just removed from the default libraries.

I added the missing rgb-led-v2-rescue, it was created by kicad while importing the project.

**Comment by dbrgn** [comment]
Ok :) I think there are more libraries that could be removed, like `xilinx`. Not important though.

**Comment by dbrgn** [comment]
Some parts in the schema aren't rendered correctly so far.

mosfet

Same thing with the LED- and VCC-connectors:

conn

Does this stuff look OK on your computer?

**Comment by rnestler** [comment]
It looks good on my machine :confused:

**Comment by dns2utf8** [comment]
Can you clone the repo in the same machine again ensuring everything is checked in?

**Comment by rnestler** [comment]
@dns2utf8 Does it work on your machine? I used KiCad 4.0.2. I can try a clean checkout later.

**Comment by rnestler** [comment]
OK I cloned it cleanly and it isn't rendered correctly. I now added the cache library from the old checkout and now it works.

**Comment by dbrgn** [comment]
I think it looks good now!

**Comment by dbrgn** [comment]
I pushed a commit that fixes some issues that the ERC reported (missing power flags between fuse and switch). Sorry for not following the usual protocol, but fixing this is easier than explaining what to change - it's KiCAD after all :) If you disagree just remove my commit.

**Comment by dbrgn** [comment]
Can this be merged now, @rnestler?

**Comment by rnestler** [comment]
@dbrgn It has a lot of strange whitespace changes in your commit and some other random changes which I have no idea. But since it works...

**Comment by dbrgn** [comment]
No idea about those, probably slightly different KiCAD versions with an unstable file format... :/ Hello LibrePCB.

Feel free to merge!

**Pull request merged**
